kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-web-2-manager
  # replace with namespace where provisioner is deployed
  namespace: test-web-2
subjects:
  - kind: ServiceAccount
    name: test-sa-2
    # replace with namespace where provisioner is deployed
    namespace: test-web-2
roleRef:
  kind: Role
  name: test-web-2-manager
  apiGroup: rbac.authorization.k8s.io