kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-pods-in-test-web-1
  # replace with namespace where provisioner is deployed
  namespace: test-web-1
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "patch"] # , "create", "update", "patch"