apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-local-cert
spec:
  # Secret names are always required.
  secretName: test-local-tls
  isCA: false
  issuerRef:
    name: test-ca-issuer
    kind: Issuer
  commonName: "test.local"
  dnsNames:
    - test.local
