apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-web-2-autoscaling
  namespace: test-web-2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-web-2-deployment
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 1