# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-test-web-2
  name: test-web-2-service
  namespace: test-web-2
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  selector:
    project: test-web-2-frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80