apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  imagePullSecrets:
    - name: docker-registry-key
  containers:
    - name: my-nginx
      image: nexus.dib:5000/nginx:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 80