# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: k8s-test-web-1
#   name: test-web-1-service
#   namespace: test-web-1
# spec:
#   type: NodePort
#   externalTrafficPolicy: Local # Cluser - доступен на порту на всех нодах, Local - доступен на порту на ноде на которой запущен контейнер
#   selector:
#     project: test-web-1-frontend
#   ports:
#   - nodePort: 32097
#     port: 80
#     protocol: TCP
#     targetPort: 80

apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-test-web-1
  name: test-web-1-service
  namespace: test-web-1
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  selector:
    project: test-web-1-frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80



