apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-web-1-pvc
  namespace: test-web-1
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: test-web-1-pv
