kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-web-2-pvc-provisioner
  namespace: test-web-2
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi