---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-main
  labels:
    storage: basemain 
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  local:
    path: /var/pgsql-volume
  storageClassName: storage-main
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: db
              operator: In
              values:
               - pgsql-main
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-replica
  labels:
    storage: basereplica
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  local:
    path: /var/pgsql-volume
  storageClassName: storage-replica
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: db
              operator: In
              values:
               - pgsql-replica
  persistentVolumeReclaimPolicy: Retain
