kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-pods-in-test-web-1
  # replace with namespace where provisioner is deployed
  namespace: test-web-1
subjects:
  - kind: ServiceAccount
    name: test-sa
    # replace with namespace where provisioner is deployed
    namespace: test-web-1
roleRef:
  kind: Role
  name: get-pods-in-test-web-1
  apiGroup: rbac.authorization.k8s.io